DROP TABLE IF EXISTS posts;


CREATE TABLE posts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    content TEXT NOT NULL
);

DROP TABLE IF EXISTS login;

CREATE TABLE login (
    user_id INTEGER PRIMARY KEY AUTOINCREMENT,
    email text not NULL,
    password text not NULL
)

